baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Generative AI: A Guide for Lawyers and Law Students'
theme = 'hugo-initio'

[params]
    name = "Generative AI"
    description = "A guide for lawyers and law students"
    phone = ""
    address = "584 Castro St #207, San Francisco, CA 94114"
    year = 2023
    avatar = "images/icon.png"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head_new.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "David S. Kemp"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/davidskemp"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/davidskemp"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/davidskemp"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/dskemp"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:david@genai.law"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"